import { PrismaClient, Equipment, Difficulty } from "@prisma/client"

const prisma = new PrismaClient()

const exercises = [
  // ── COMPOUND BARBELL ──────────────────────────────────────────────────────
  { name: "Squat", nameAlt: "Back Squat", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["HAMSTRING", "LOWER_BACK", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Il re degli esercizi per le gambe. Il bilanciere poggia sul trapezo, la discesa porta le cosce parallele al suolo o più in basso.", tips: "Piedi larghezza spalle, punte leggermente fuori. Spingi le ginocchia verso l'esterno in linea con le punte. Mantieni il petto alto e la schiena neutra. Inspira in discesa, espira in salita." },
  { name: "Stacco da Terra", nameAlt: "Deadlift", primaryMuscles: ["HAMSTRING", "GLUTE", "LOWER_BACK"], secondaryMuscles: ["QUAD", "UPPER_BACK", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Esercizio di trazione da terra. Coinvolge la catena posteriore completa.", tips: "Barra sopra il metatarso, presa a larghezza delle anche. Abbassa il bacino finché le tibie toccano la barra. Spingi il suolo lontano da te. Non arrotondare la schiena lombare." },
  { name: "Stacco Rumeno", nameAlt: "Romanian Deadlift / RDL", primaryMuscles: ["HAMSTRING", "GLUTE"], secondaryMuscles: ["LOWER_BACK", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Variante dello stacco con ginocchia semi-flesse, enfasi massima sui femorali.", tips: "Partenza in piedi, barra contro i fianchi. Spingi il bacino indietro mantenendo la schiena neutra. Fermati quando senti tensione nei femorali, non necessariamente quando la barra tocca il suolo." },
  { name: "Panca Piana", nameAlt: "Bench Press", primaryMuscles: ["CHEST"], secondaryMuscles: ["SHOULDER", "TRICEP"], equipment: Equipment.BARBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Esercizio di spinta orizzontale, principale per lo sviluppo del petto.", tips: "5 punti di contatto: testa, spalle, glutei, piedi. Retrai e deprimi le scapole. Tocca il petto con la barra a livello dei capezzoli. Gomiti a 45-75° dal busto." },
  { name: "Panca Inclinata", nameAlt: "Incline Bench Press", primaryMuscles: ["CHEST"], secondaryMuscles: ["SHOULDER", "TRICEP"], equipment: Equipment.BARBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Spinta su panca inclinata a 30-45°, enfasi sul fascio clavicolare del pettorale.", tips: "Angolo ottimale: 30-45°. A 45° aumenta molto il coinvolgimento delle spalle. Stesso setup scapolare della panca piana." },
  { name: "Military Press", nameAlt: "Overhead Press / OHP", primaryMuscles: ["SHOULDER"], secondaryMuscles: ["TRICEP", "UPPER_BACK", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Spinta verticale sopra la testa. Sviluppa spalle e tricipiti e richiede grande stabilità del core.", tips: "Presa leggermente più larga delle spalle. Barra sulla clavicola, gomiti leggermente davanti alla barra. Spinge la testa in avanti mentre la barra sale. Glutei e addome tesi per stabilità." },
  { name: "Rematore con Bilanciere", nameAlt: "Barbell Row / Bent Over Row", primaryMuscles: ["UPPER_BACK"], secondaryMuscles: ["BICEP", "LOWER_BACK", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Trazione orizzontale fondamentale per la schiena. Bilanciere tirato verso l'ombelico con busto inclinato.", tips: "Busto a 45° o parallelo al suolo. Tira verso l'ombelico, non verso il petto. Retrai le scapole in alto al movimento. Ginocchia leggermente flesse." },
  { name: "Trazioni", nameAlt: "Pull-up / Chin-up", primaryMuscles: ["UPPER_BACK"], secondaryMuscles: ["BICEP", "CORE"], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Trazione verticale al proprio peso. Pull-up (presa prona) o Chin-up (presa supina, più bicipiti).", tips: "Partenza con braccia completamente estese (dead hang). Spingi i gomiti verso terra e verso il corpo. Porta il mento sopra la barra. Evita lo swing del corpo." },
  { name: "Affondi", nameAlt: "Lunges", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["HAMSTRING", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Esercizio unilaterale per gambe e glutei. Ottimo per correggere asimmetrie.", tips: "Passo lungo (anteriore), ginocchio posteriore sfiora il suolo. Ginocchio anteriore non supera la punta del piede. Busto eretto. Eseguire anche con manubri." },
  { name: "Leg Press", nameAlt: "Pressa", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["HAMSTRING"], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Macchina per la spinta delle gambe. Permette carichi elevati in sicurezza.", tips: "Piedi alti e larghi = più glutei/femorali. Piedi bassi e stretti = più quadricipiti. Non bloccare le ginocchia in estensione." },
  { name: "Hip Thrust", nameAlt: "Glutei con bilanciere", primaryMuscles: ["GLUTE"], secondaryMuscles: ["HAMSTRING", "CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Il miglior esercizio per l'attivazione e il volume dei glutei. Schiena sulla panca, bilanciere sui fianchi.", tips: "Mento al petto, non iperestendere la colonna. Spingi attraverso i talloni. Contrai i glutei in alto per 1-2 secondi. Ginocchia in linea con i piedi." },
  { name: "Good Morning", primaryMuscles: ["HAMSTRING", "LOWER_BACK", "GLUTE"], secondaryMuscles: ["CORE"], equipment: Equipment.BARBELL, difficulty: Difficulty.ADVANCED, isCompound: true, description: "Flessione del busto con bilanciere sulle spalle. Ottimo per rinforzare femorali e schiena.", tips: "Inizia con carichi leggeri. Ginocchia semi-flesse. Abbassa il busto finché è parallelo al suolo. Non arrotondare la lombare." },

  // ── DUMBBELL COMPOUND ─────────────────────────────────────────────────────
  { name: "Panca Manubri", nameAlt: "Dumbbell Bench Press", primaryMuscles: ["CHEST"], secondaryMuscles: ["SHOULDER", "TRICEP"], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Variante della panca con manubri. Maggiore ROM e stimolo stabilizzatore.", tips: "Porta i manubri a contatto con il petto. Sposta i polsi direttamente sopra i gomiti. Maggiore ROM rispetto al bilanciere." },
  { name: "Panca Inclinata Manubri", primaryMuscles: ["CHEST"], secondaryMuscles: ["SHOULDER", "TRICEP"], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Spinta inclinata con manubri. Ottima per il petto superiore.", tips: "Angolo panca 30-45°. Porta i manubri verso le clavicole." },
  { name: "Shoulder Press Manubri", nameAlt: "Dumbbell Overhead Press", primaryMuscles: ["SHOULDER"], secondaryMuscles: ["TRICEP"], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Spinta sopra la testa con manubri. Ottima per correggere asimmetrie destra/sinistra.", tips: "Seduto o in piedi. Manubri all'altezza delle orecchie, gomiti a 90°. Spingi verticalmente." },
  { name: "Rematore Manubrio", nameAlt: "One-arm Dumbbell Row", primaryMuscles: ["UPPER_BACK"], secondaryMuscles: ["BICEP"], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Trazione unilaterale con appoggio sulla panca. Ottimo per la schiena.", tips: "Schiena parallela al suolo, appoggio con mano e ginocchio. Tira il gomito verso il soffitto, non verso la spalla." },

  // ── CABLE ─────────────────────────────────────────────────────────────────
  { name: "Lat Machine", nameAlt: "Lat Pulldown", primaryMuscles: ["UPPER_BACK"], secondaryMuscles: ["BICEP"], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Trazione verticale alla macchina. Alternativa alle trazioni per principianti o per volume aggiuntivo.", tips: "Inclinati leggermente indietro. Tira verso il petto, non dietro la nuca. Spingi i gomiti verso il bacino." },
  { name: "Pulley Basso", nameAlt: "Seated Cable Row / Low Row", primaryMuscles: ["UPPER_BACK"], secondaryMuscles: ["BICEP", "LOWER_BACK"], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Trazione orizzontale al cavo basso. Costante tensione durante tutto il ROM.", tips: "Busto eretto, non oscillare. Tira verso l'ombelico. Retrai le scapole alla fine del movimento." },
  { name: "Cable Crossover", nameAlt: "Croci ai cavi", primaryMuscles: ["CHEST"], secondaryMuscles: [], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del petto ai cavi alti. Tensione costante a differenza delle croci con manubri.", tips: "Busto leggermente inclinato in avanti. Porta le mani a incontrarsi davanti al petto o sotto. Mantieni i gomiti leggermente flessi." },
  { name: "Face Pull", primaryMuscles: ["SHOULDER", "UPPER_BACK"], secondaryMuscles: [], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Esercizio correttivo per salute della spalla. Rinforza rotatori esterni e deltoide posteriore.", tips: "Cavo all'altezza degli occhi. Tira verso il viso aprendo i gomiti. Fondamentale per la salute della cuffia." },
  { name: "Pushdown Tricipiti", nameAlt: "Tricep Pushdown", primaryMuscles: ["TRICEP"], secondaryMuscles: [], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento dei tricipiti al cavo alto. Con barra dritta, barra curva o corda.", tips: "Gomiti fissi ai fianchi. Estensione completa. Con la corda, apri le mani in basso per maggiore contrazione." },
  { name: "Curl ai Cavi", nameAlt: "Cable Curl", primaryMuscles: ["BICEP"], secondaryMuscles: [], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Curl bicipiti al cavo basso. Tensione costante durante tutto il ROM.", tips: "Gomiti fissi ai fianchi. Supina il polso in cima al movimento." },
  { name: "Alzate Laterali al Cavo", primaryMuscles: ["SHOULDER"], secondaryMuscles: [], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Variante delle alzate laterali con tensione iniziale dal basso.", tips: "Cavo dal basso, braccio opposto. Porta il braccio all'altezza della spalla." },

  // ── MACHINE ───────────────────────────────────────────────────────────────
  { name: "Chest Press", nameAlt: "Panca Macchina", primaryMuscles: ["CHEST"], secondaryMuscles: ["SHOULDER", "TRICEP"], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Spinta orizzontale alla macchina. Ottima per principianti o come esercizio di pump finale.", tips: "Regola il sedile in modo che le maniglie siano all'altezza del petto. Concentrati sulla contrazione del petto." },
  { name: "Leg Curl", nameAlt: "Curl Femorali", primaryMuscles: ["HAMSTRING"], secondaryMuscles: [], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento dei femorali sdraiato o seduto. Fondamentale per il volume dei femorali.", tips: "Sdraiato: tibiotarsica a 90°, non sollevare i fianchi. Mantieni la contrazione in cima." },
  { name: "Leg Extension", nameAlt: "Estensione Quadricipiti", primaryMuscles: ["QUAD"], secondaryMuscles: [], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento dei quadricipiti. Ottimo come esercizio finale.", tips: "Non iperestendere il ginocchio. Mantieni la contrazione in cima 1-2 secondi." },
  { name: "Pec Deck", nameAlt: "Croci alla Macchina", primaryMuscles: ["CHEST"], secondaryMuscles: [], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del petto alla macchina. Tensione costante.", tips: "Gomiti leggermente flessi. Non portare i gomiti oltre le spalle per proteggere l'articolazione." },
  { name: "Shoulder Press Macchina", primaryMuscles: ["SHOULDER"], secondaryMuscles: ["TRICEP"], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Spinta verticale alla macchina. Guidata e sicura.", tips: "Regola il sedile correttamente. Buon esercizio per volume extra o per chi ha problemi di schiena." },
  { name: "Rowing Macchina", primaryMuscles: ["UPPER_BACK"], secondaryMuscles: ["BICEP"], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Trazione orizzontale guidata.", tips: "Petto appoggiato al supporto. Tira verso il petto, retrai le scapole." },
  { name: "Calf Raise", nameAlt: "Punta Piedi", primaryMuscles: ["CALF"], secondaryMuscles: [], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del polpaccio. Eseguibile in piedi o seduto.", tips: "ROM completo: scendi fino all'allungamento massimo. Pausa di 1s in cima. Volume alto (12-20 rip) per i polpacci." },
  { name: "Hack Squat", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["HAMSTRING"], equipment: Equipment.MACHINE, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Squat alla macchina con schiena guidata. Ottimo per il volume di gambe.", tips: "Piedi in avanti sulla piattaforma per maggiore ROM. Non bloccare le ginocchia." },

  // ── DUMBBELL ISOLATION ────────────────────────────────────────────────────
  { name: "Curl Bilanciere", nameAlt: "Barbell Curl", primaryMuscles: ["BICEP"], secondaryMuscles: [], equipment: Equipment.BARBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento classico dei bicipiti con bilanciere.", tips: "Gomiti fissi ai fianchi. Non oscillare il busto. Supina i polsi in cima." },
  { name: "Curl Manubri", nameAlt: "Dumbbell Curl", primaryMuscles: ["BICEP"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Curl bicipiti con manubri. Eseguibile alternato o simultaneo.", tips: "Supina il polso durante la flessione. Porta il mignolo verso la spalla in cima." },
  { name: "Curl Martello", nameAlt: "Hammer Curl", primaryMuscles: ["BICEP"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Curl con presa neutra (pollice in alto). Coinvolge anche il brachioradiale.", tips: "Presa neutra durante tutto il movimento. Buono per i muscoli dell'avambraccio." },
  { name: "French Press", nameAlt: "Skull Crushers / EZ Bar Tricep Extension", primaryMuscles: ["TRICEP"], secondaryMuscles: [], equipment: Equipment.BARBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Estensione del tricipite sdraiato con bilanciere EZ. Ottimo per la testa lunga.", tips: "Porta la barra verso la fronte o la testa piegando i gomiti. Gomiti fissi in posizione." },
  { name: "Dips", nameAlt: "Parallele", primaryMuscles: ["TRICEP", "CHEST"], secondaryMuscles: ["SHOULDER"], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Spinta alle parallele. Con busto eretto enfatizza i tricipiti; inclinato in avanti il petto.", tips: "Busto eretto per tricipiti, inclinato per petto. Scendi fino a 90° di gomito. Aggiungere peso con cintura apposita." },
  { name: "Croci Manubri", nameAlt: "Dumbbell Fly", primaryMuscles: ["CHEST"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del petto con manubri. Grande allungamento del pettorale.", tips: "Manubri si incontrano sopra il petto ma non si toccano. Gomiti leggermente flessi per tutto il movimento." },
  { name: "Alzate Laterali", nameAlt: "Lateral Raises", primaryMuscles: ["SHOULDER"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del deltoide laterale. Volume alto (15-25 rip) con carichi leggeri.", tips: "Porta i manubri fino all'altezza delle spalle. Gomiti leggermente flessi. Pinky finger leggermente sopra il pollice (come versare una bottiglia)." },
  { name: "Alzate Frontali", nameAlt: "Front Raises", primaryMuscles: ["SHOULDER"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del deltoide anteriore.", tips: "Porta il braccio all'altezza della spalla. Non oscillare il busto." },
  { name: "Alzate Posteriori", nameAlt: "Rear Delt Fly / Reverse Fly", primaryMuscles: ["SHOULDER", "UPPER_BACK"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isolamento del deltoide posteriore. Spesso trascurato ma fondamentale per la salute della spalla.", tips: "Busto inclinato o sdraiato a faccia in giù. Porta i gomiti verso il soffitto." },
  { name: "Tricep Overhead Extension", primaryMuscles: ["TRICEP"], secondaryMuscles: [], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Estensione del tricipite sopra la testa. Allunga la testa lunga del tricipite.", tips: "Tieni il braccio verticale, piega solo il gomito. Ottimo per la testa lunga del tricipite." },

  // ── CORE ──────────────────────────────────────────────────────────────────
  { name: "Plank", primaryMuscles: ["CORE"], secondaryMuscles: ["SHOULDER"], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Isometria del core. Mantieni la posizione per il tempo prescritto.", tips: "Corpo in linea dalla testa ai talloni. Non alzare i fianchi né farli cadere. Respira regolarmente." },
  { name: "Ab Wheel", nameAlt: "Rollout addominali", primaryMuscles: ["CORE"], secondaryMuscles: ["SHOULDER", "UPPER_BACK"], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.INTERMEDIATE, isCompound: false, description: "Esercizio avanzato per il core con ruota. Allunga e stabilizza l'addome.", tips: "Inizia con rollout parziale. Mantieni la schiena piatta durante tutto il movimento." },
  { name: "Cable Crunch", primaryMuscles: ["CORE"], secondaryMuscles: [], equipment: Equipment.CABLE, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Crunch al cavo alto. Permette di aggiungere carico progressivo agli addominali.", tips: "Inginocchiato, tira il cavo verso il suolo arrotondando la schiena. Non flettere le anche, muovi solo la colonna." },
  { name: "Leg Raise", nameAlt: "Alzate gambe", primaryMuscles: ["CORE"], secondaryMuscles: [], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Alzata delle gambe sdraiato. Lavora sulla parte bassa degli addominali.", tips: "Schiena piatta sul suolo. Se troppo facile, aggiungi peso alle caviglie o esegui alle parallele." },
  { name: "Crunch", primaryMuscles: ["CORE"], secondaryMuscles: [], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Crunch classico. Esegui con ROM completo.", tips: "Non tirare il collo con le mani. Concentrati sulla contrazione degli addominali." },
  { name: "Russian Twist", primaryMuscles: ["CORE"], secondaryMuscles: [], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.BEGINNER, isCompound: false, description: "Rotazione del busto per il core obliquo. Con o senza peso.", tips: "Piedi sollevati per maggiore difficoltà. Ruota le spalle, non solo le braccia." },

  // ── CARDIO / FUNCTIONAL ───────────────────────────────────────────────────
  { name: "Corsa", nameAlt: "Running", primaryMuscles: ["QUAD", "HAMSTRING", "CALF"], secondaryMuscles: ["CORE", "GLUTE"], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Cardio aerobico. Monitorare distanza, tempo, passo e FC.", tips: "Zone 2 (60-70% FCmax) per adattamenti aerobici. Non aumentare volume di più del 10%/settimana." },
  { name: "Kettlebell Swing", primaryMuscles: ["GLUTE", "HAMSTRING"], secondaryMuscles: ["CORE", "LOWER_BACK", "SHOULDER"], equipment: Equipment.KETTLEBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Ballistica con kettlebell. Sviluppa potenza della catena posteriore e condizionamento.", tips: "Il swing è una spinta dei fianchi, non un sollevamento delle braccia. Glutei contratti in cima." },
  { name: "Goblet Squat", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["CORE"], equipment: Equipment.KETTLEBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Squat con kettlebell o manubrio al petto. Ottimo per imparare la meccanica dello squat.", tips: "Kettlebell a petto. Gomiti tra le ginocchia in discesa. Schiena eretta." },
  { name: "Step Up", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["HAMSTRING"], equipment: Equipment.DUMBBELL, difficulty: Difficulty.BEGINNER, isCompound: true, description: "Salita su rialzo unilaterale. Ottimo per correggere asimmetrie.", tips: "Piede completo sul rialzo, spingi verso il basso per salire. Non rimbalzare con il piede di terra." },
  { name: "Bulgarian Split Squat", nameAlt: "Squat bulgaro", primaryMuscles: ["QUAD", "GLUTE"], secondaryMuscles: ["HAMSTRING"], equipment: Equipment.DUMBBELL, difficulty: Difficulty.INTERMEDIATE, isCompound: true, description: "Squat unilaterale con piede posteriore elevato. Eccellente per quadricipiti e glutei.", tips: "Piede posteriore sulla panca. Scendi verticalmente. Ginocchio anteriore in linea con il piede." },
  { name: "Nordic Curl", nameAlt: "Leg Curl a corpo libero", primaryMuscles: ["HAMSTRING"], secondaryMuscles: [], equipment: Equipment.BODYWEIGHT, difficulty: Difficulty.ADVANCED, isCompound: false, description: "Esercizio eccentrico intenso per i femorali. Preventivo per gli infortuni muscolari.", tips: "Piedi bloccati, scendi il più lentamente possibile. Inizia aiutandoti con le mani in discesa." },
]

async function main() {
  console.log("🌱 Seeding exercise library...")

  let count = 0
  for (const ex of exercises) {
    await prisma.exerciseDefinition.upsert({
      where: { name: ex.name },
      update: {},
      create: {
        name: ex.name,
        nameAlt: ex.nameAlt ?? null,
        primaryMuscles: ex.primaryMuscles as any,
        secondaryMuscles: ex.secondaryMuscles as any,
        equipment: ex.equipment,
        difficulty: ex.difficulty,
        isCompound: ex.isCompound,
        description: ex.description ?? null,
        tips: ex.tips ?? null,
      },
    })
    count++
  }

  // NOTE: SessionStressDefinition was removed from schema (Step 4 refactor).
  // DistrictStress is now calculated dynamically from real SetLog data.
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
