/**
 * Database alimenti italiani — valori per 100 g/ml
 * Fonte: INRAN (Istituto Nazionale di Ricerca per gli Alimenti e la Nutrizione)
 *        + valori standard internazionali USDA + IEO (Istituto Europeo di Oncologia)
 */
export type Food = {
  name: string
  kcal: number
  p: number   // proteine g
  c: number   // carboidrati g
  f: number   // grassi g
  tags?: string[]   // parole chiave extra per la ricerca
}

export const FOODS: Food[] = [

  // ── CEREALI, PASTA & RISO ─────────────────────────────────────────────────
  { name: 'Pasta di semola (cruda)',        kcal: 353, p: 12.5, c: 70.2, f: 1.4,  tags: ['pasta cruda', 'spaghetti', 'penne', 'rigatoni', 'fusilli', 'maccheroni'] },
  { name: 'Pasta di semola (cotta)',        kcal: 158, p: 5.8,  c: 30.6, f: 0.9,  tags: ['pasta cotta', 'spaghetti cotti', 'penne cotte'] },
  { name: 'Pasta integrale (cruda)',        kcal: 335, p: 13.4, c: 63.6, f: 2.5,  tags: ['pasta integrale cruda'] },
  { name: 'Pasta integrale (cotta)',        kcal: 150, p: 5.3,  c: 28.1, f: 1.0,  tags: ['pasta integrale cotta'] },
  { name: 'Pasta all\'uovo (cruda)',        kcal: 368, p: 13.5, c: 68.4, f: 4.2,  tags: ['tagliatelle crude', 'pappardelle crude', 'egg pasta'] },
  { name: 'Pasta all\'uovo (cotta)',        kcal: 172, p: 6.3,  c: 30.2, f: 2.3,  tags: ['tagliatelle cotte', 'pappardelle cotte'] },
  { name: 'Gnocchi di patate',             kcal: 130, p: 3.5,  c: 26.0, f: 0.8,  tags: ['gnocchi'] },
  { name: 'Riso bianco (crudo)',            kcal: 358, p: 7.5,  c: 79.3, f: 0.4,  tags: ['riso crudo'] },
  { name: 'Riso bianco (cotto)',            kcal: 130, p: 2.7,  c: 28.2, f: 0.3,  tags: ['riso cotto', 'riso in bianco'] },
  { name: 'Riso integrale (crudo)',         kcal: 350, p: 7.9,  c: 73.1, f: 2.7,  tags: ['riso integrale crudo'] },
  { name: 'Riso integrale (cotto)',         kcal: 123, p: 2.6,  c: 25.6, f: 1.0,  tags: ['riso integrale cotto'] },
  { name: 'Riso basmati (cotto)',           kcal: 121, p: 3.5,  c: 25.2, f: 0.4,  tags: ['basmati'] },
  { name: 'Riso venere (cotto)',            kcal: 110, p: 3.0,  c: 23.0, f: 1.0,  tags: ['riso nero'] },
  { name: 'Riso parboiled (cotto)',         kcal: 124, p: 3.0,  c: 26.6, f: 0.3 },
  { name: 'Pane comune',                   kcal: 275, p: 8.1,  c: 53.8, f: 0.5,  tags: ['pane bianco', 'michetta', 'filone', 'rosetta'] },
  { name: 'Pane integrale',                kcal: 224, p: 8.5,  c: 40.5, f: 1.9,  tags: ['pane integrale'] },
  { name: 'Pane di segale',                kcal: 219, p: 5.9,  c: 45.2, f: 1.7,  tags: ['pane di segale'] },
  { name: 'Pane ai cereali',               kcal: 248, p: 9.2,  c: 44.5, f: 3.2,  tags: ['pane cereali', 'pane multicereali'] },
  { name: 'Panino (tipo kaiser)',           kcal: 279, p: 9.0,  c: 53.0, f: 2.9,  tags: ['panino', 'rosetta', 'semelle'] },
  { name: 'Piadina',                       kcal: 300, p: 8.0,  c: 48.0, f: 8.5,  tags: ['piadina'] },
  { name: 'Focaccia (plain)',              kcal: 282, p: 7.5,  c: 42.0, f: 8.5,  tags: ['focaccia'] },
  { name: 'Grissini',                      kcal: 412, p: 10.5, c: 69.0, f: 9.0,  tags: ['grissino'] },
  { name: 'Fette biscottate',              kcal: 410, p: 8.8,  c: 75.3, f: 8.4,  tags: ['fette biscottate'] },
  { name: 'Fette biscottate integrali',    kcal: 382, p: 9.5,  c: 68.1, f: 6.9,  tags: ['fette biscottate integrali'] },
  { name: 'Avena (fiocchi)',               kcal: 389, p: 16.9, c: 66.3, f: 6.9,  tags: ['porridge', 'oats', 'fiocchi d\'avena', 'fiocchi avena'] },
  { name: 'Polenta (cotta)',               kcal: 70,  p: 1.8,  c: 15.0, f: 0.4,  tags: ['polenta', 'mais', 'farina di mais'] },
  { name: 'Polenta (cruda — farina)',      kcal: 362, p: 8.7,  c: 76.0, f: 3.6,  tags: ['farina di mais granoturco'] },
  { name: 'Orzo perlato (crudo)',          kcal: 352, p: 9.9,  c: 70.2, f: 2.1,  tags: ['orzo'] },
  { name: 'Orzo perlato (cotto)',          kcal: 123, p: 2.3,  c: 28.2, f: 0.4 },
  { name: 'Farro (cotto)',                 kcal: 150, p: 5.8,  c: 28.7, f: 1.0,  tags: ['farro'] },
  { name: 'Farro (crudo)',                 kcal: 338, p: 14.7, c: 65.0, f: 2.5,  tags: ['farro crudo'] },
  { name: 'Grano saraceno',               kcal: 343, p: 13.2, c: 63.0, f: 3.4,  tags: ['buckwheat', 'grano saraceno'] },
  { name: 'Quinoa (cotta)',               kcal: 120, p: 4.4,  c: 21.3, f: 1.9,  tags: ['quinoa'] },
  { name: 'Couscous (cotto)',             kcal: 112, p: 3.8,  c: 23.2, f: 0.2,  tags: ['couscous', 'cous cous'] },
  { name: 'Amaranto (cotto)',             kcal: 102, p: 3.8,  c: 18.7, f: 1.6,  tags: ['amaranto'] },
  { name: 'Miglio (cotto)',               kcal: 119, p: 3.5,  c: 23.7, f: 1.0,  tags: ['miglio'] },
  { name: 'Crackers',                     kcal: 428, p: 8.0,  c: 69.8, f: 12.0, tags: ['crackers'] },
  { name: 'Gallette di riso',             kcal: 387, p: 7.3,  c: 80.8, f: 2.8,  tags: ['gallette riso'] },
  { name: 'Corn flakes',                  kcal: 380, p: 7.5,  c: 84.0, f: 0.8,  tags: ['cereali', 'corn flakes', 'fiocchi di mais'] },
  { name: 'Muesli',                       kcal: 380, p: 9.5,  c: 65.0, f: 9.0,  tags: ['müsli', 'musli', 'cereali colazione'] },
  { name: 'Granola',                      kcal: 450, p: 10.0, c: 62.0, f: 17.0, tags: ['granola'] },
  { name: 'Pan carré',                    kcal: 270, p: 9.5,  c: 48.5, f: 3.5,  tags: ['pane in cassetta', 'toast', 'tramezzino'] },
  { name: 'Taralli',                      kcal: 416, p: 9.5,  c: 64.0, f: 12.5, tags: ['taralli'] },
  { name: 'Pasta e fagioli (piatto)',     kcal: 105, p: 5.5,  c: 16.0, f: 2.0,  tags: ['pasta fagioli', 'pasta e fagioli'] },

  // ── CARNI BIANCHE ─────────────────────────────────────────────────────────
  { name: 'Petto di pollo (cotto)',        kcal: 165, p: 31.0, c: 0.0,  f: 3.6,  tags: ['pollo petto cotto', 'chicken breast'] },
  { name: 'Petto di pollo (crudo)',        kcal: 110, p: 23.1, c: 0.0,  f: 1.2,  tags: ['pollo petto crudo'] },
  { name: 'Coscia di pollo (cotta)',       kcal: 209, p: 25.9, c: 0.0,  f: 10.9, tags: ['coscia pollo cotta'] },
  { name: 'Coscia di pollo (cruda)',       kcal: 143, p: 17.2, c: 0.0,  f: 7.9,  tags: ['coscia pollo cruda'] },
  { name: 'Pollo intero arrosto',          kcal: 190, p: 24.7, c: 0.0,  f: 10.0, tags: ['pollo arrosto', 'pollo al forno'] },
  { name: 'Alette di pollo (cotte)',       kcal: 222, p: 20.6, c: 0.0,  f: 15.3, tags: ['alette pollo', 'ali di pollo', 'chicken wings'] },
  { name: 'Pollo alla cacciatora',         kcal: 152, p: 17.0, c: 4.5,  f: 6.8,  tags: ['pollo cacciatora'] },
  { name: 'Pollo in padella con verdure',  kcal: 130, p: 18.0, c: 5.0,  f: 4.5,  tags: ['pollo verdure', 'pollo saltato'] },
  { name: 'Tacchino petto (cotto)',        kcal: 135, p: 29.9, c: 0.0,  f: 1.6,  tags: ['tacchino petto cotto', 'turkey'] },
  { name: 'Tacchino petto (crudo)',        kcal: 104, p: 22.0, c: 0.5,  f: 1.1,  tags: ['tacchino crudo'] },
  { name: 'Tacchino (macinato)',           kcal: 148, p: 20.4, c: 0.0,  f: 7.3,  tags: ['tacchino macinato'] },
  { name: 'Coniglio (cotto)',              kcal: 197, p: 30.3, c: 0.0,  f: 8.0,  tags: ['coniglio'] },
  { name: 'Anatra (petto, cotta)',         kcal: 201, p: 23.5, c: 0.0,  f: 11.2, tags: ['anatra', 'petto d\'anatra'] },
  { name: 'Fagiano (cotto)',               kcal: 163, p: 24.3, c: 0.0,  f: 6.9,  tags: ['fagiano', 'selvaggina'] },

  // ── CARNI ROSSE ────────────────────────────────────────────────────────────
  { name: 'Manzo (bistecca magra)',        kcal: 179, p: 26.1, c: 0.0,  f: 7.9,  tags: ['bistecca', 'manzo', 'beef'] },
  { name: 'Manzo (macinato 5% grassi)',    kcal: 137, p: 21.4, c: 0.0,  f: 5.4,  tags: ['macinato magro', 'carne macinata magra'] },
  { name: 'Manzo (macinato 20% grassi)',   kcal: 254, p: 17.2, c: 0.0,  f: 20.0, tags: ['macinato grasso'] },
  { name: 'Filetto di manzo (cotto)',      kcal: 192, p: 27.0, c: 0.0,  f: 9.0,  tags: ['filetto manzo', 'filet mignon'] },
  { name: 'Controfiletto di manzo',        kcal: 214, p: 25.0, c: 0.0,  f: 12.0, tags: ['controfiletto', 'sirloin'] },
  { name: 'Scamone di manzo',             kcal: 166, p: 25.0, c: 0.0,  f: 7.0,  tags: ['scamone', 'fesa di manzo'] },
  { name: 'Hamburger di manzo (cotto)',    kcal: 220, p: 22.0, c: 1.5,  f: 14.0, tags: ['hamburger', 'burger di manzo'] },
  { name: 'Carpaccio di manzo',            kcal: 120, p: 20.5, c: 0.0,  f: 4.5,  tags: ['carpaccio'] },
  { name: 'Fegato di manzo (cotto)',       kcal: 175, p: 27.0, c: 5.0,  f: 5.0,  tags: ['fegato manzo'] },
  { name: 'Maiale (lonza)',               kcal: 143, p: 21.5, c: 0.0,  f: 5.9,  tags: ['lonza di maiale', 'pork loin'] },
  { name: 'Maiale (costine)',             kcal: 233, p: 18.0, c: 0.0,  f: 17.9, tags: ['costine maiale', 'spare ribs'] },
  { name: 'Maiale (braciola)',            kcal: 204, p: 22.8, c: 0.0,  f: 12.3, tags: ['braciola', 'bistecca di maiale'] },
  { name: 'Maiale (arrosto)',             kcal: 220, p: 28.5, c: 0.0,  f: 11.5, tags: ['arrosto di maiale'] },
  { name: 'Salsiccia fresca (cruda)',     kcal: 301, p: 16.0, c: 1.5,  f: 26.0, tags: ['salsiccia'] },
  { name: 'Salsiccia (cotta alla griglia)', kcal: 268, p: 19.0, c: 1.0, f: 21.0, tags: ['salsiccia cotta', 'salsicce'] },
  { name: 'Agnello (coscia)',             kcal: 206, p: 26.7, c: 0.0,  f: 10.7, tags: ['agnello', 'lamb'] },
  { name: 'Agnello (costolette)',         kcal: 294, p: 25.6, c: 0.0,  f: 20.5, tags: ['costolette agnello'] },
  { name: 'Vitello (fesa)',              kcal: 107, p: 19.6, c: 0.0,  f: 2.9,  tags: ['vitello', 'veal'] },
  { name: 'Vitello (cotoletta impanata)', kcal: 230, p: 18.0, c: 10.5, f: 12.5, tags: ['cotoletta', 'cotoletta milanese', 'scaloppina impanata'] },
  { name: 'Scaloppine di vitello',        kcal: 125, p: 21.0, c: 0.5,  f: 4.0,  tags: ['scaloppine', 'scaloppina'] },
  { name: 'Fegato di pollo (cotto)',      kcal: 140, p: 22.0, c: 1.5,  f: 4.8,  tags: ['fegato pollo', 'fegatini'] },

  // ── SALUMI & AFFETTATI ────────────────────────────────────────────────────
  { name: 'Prosciutto crudo',             kcal: 268, p: 25.5, c: 0.3,  f: 17.8, tags: ['prosciutto crudo', 'San Daniele', 'di Parma'] },
  { name: 'Prosciutto cotto',             kcal: 136, p: 18.0, c: 1.3,  f: 6.0,  tags: ['prosciutto cotto'] },
  { name: 'Prosciutto cotto (alta qualità)', kcal: 120, p: 20.0, c: 0.5, f: 4.0, tags: ['prosciutto cotto magro'] },
  { name: 'Bresaola',                     kcal: 174, p: 31.0, c: 0.5,  f: 4.3,  tags: ['bresaola'] },
  { name: 'Mortadella',                   kcal: 311, p: 14.7, c: 1.5,  f: 28.0, tags: ['mortadella'] },
  { name: 'Salame',                       kcal: 387, p: 20.6, c: 1.2,  f: 33.6, tags: ['salame', 'salumi'] },
  { name: 'Salame Milano',                kcal: 407, p: 22.3, c: 0.9,  f: 35.5, tags: ['salame milano'] },
  { name: 'Speck',                        kcal: 263, p: 25.0, c: 0.5,  f: 17.3, tags: ['speck'] },
  { name: 'Pancetta affumicata',          kcal: 449, p: 11.5, c: 0.0,  f: 45.0, tags: ['pancetta', 'bacon', 'guanciale'] },
  { name: 'Coppa / Capocollo',            kcal: 334, p: 22.5, c: 0.5,  f: 26.5, tags: ['coppa', 'capocollo'] },
  { name: 'Nduja',                        kcal: 456, p: 15.0, c: 1.5,  f: 44.0, tags: ['nduja', '\'nduja'] },
  { name: 'Wurstel di pollo',             kcal: 195, p: 11.0, c: 3.0,  f: 15.0, tags: ['wurstel', 'frankfurter'] },
  { name: 'Wurstel di suino',             kcal: 249, p: 10.0, c: 2.5,  f: 22.0, tags: ['würstel', 'hot dog'] },
  { name: 'Prosciutto di Praga',          kcal: 153, p: 16.5, c: 1.0,  f: 9.3,  tags: ['praga'] },

  // ── PESCE ─────────────────────────────────────────────────────────────────
  { name: 'Tonno al naturale (sgocciolato)', kcal: 103, p: 23.3, c: 0.0, f: 0.8, tags: ['tonno naturale', 'tuna'] },
  { name: 'Tonno sott\'olio (sgocciolato)',  kcal: 198, p: 21.5, c: 0.0, f: 12.5, tags: ['tonno olio'] },
  { name: 'Salmone (cotto)',              kcal: 208, p: 20.4, c: 0.0,  f: 13.4, tags: ['salmone cotto', 'salmon'] },
  { name: 'Salmone (crudo)',              kcal: 142, p: 19.8, c: 0.0,  f: 6.3,  tags: ['salmone crudo'] },
  { name: 'Salmone affumicato',           kcal: 142, p: 21.5, c: 0.0,  f: 6.0,  tags: ['salmone affumicato', 'smoked salmon'] },
  { name: 'Merluzzo (cotto)',             kcal: 105, p: 22.8, c: 0.0,  f: 0.9,  tags: ['merluzzo', 'cod', 'baccalà'] },
  { name: 'Branzino (cotto)',             kcal: 124, p: 23.6, c: 0.0,  f: 3.0,  tags: ['branzino', 'spigola'] },
  { name: 'Orata (cotta)',                kcal: 121, p: 21.8, c: 0.0,  f: 3.6,  tags: ['orata', 'dorada'] },
  { name: 'Trota (cotta)',                kcal: 190, p: 26.6, c: 0.0,  f: 8.9,  tags: ['trota'] },
  { name: 'Trota (cruda)',                kcal: 148, p: 20.8, c: 0.0,  f: 6.9,  tags: ['trota cruda'] },
  { name: 'Pesce spada (cotto)',          kcal: 144, p: 23.2, c: 0.0,  f: 5.2,  tags: ['pesce spada'] },
  { name: 'Sgombro (cotto)',              kcal: 205, p: 22.5, c: 0.0,  f: 12.8, tags: ['sgombro', 'mackerel'] },
  { name: 'Acciughe / Alici (fresche)',   kcal: 131, p: 20.3, c: 0.0,  f: 5.3,  tags: ['alici', 'acciughe', 'anchovy'] },
  { name: 'Acciughe sott\'olio',          kcal: 210, p: 25.9, c: 0.0,  f: 12.0, tags: ['acciughe olio', 'alici olio'] },
  { name: 'Sardine sott\'olio',           kcal: 208, p: 24.6, c: 0.0,  f: 11.5, tags: ['sardine', 'sardina'] },
  { name: 'Dentice (cotto)',              kcal: 110, p: 21.5, c: 0.0,  f: 2.5,  tags: ['dentice'] },
  { name: 'Rombo (cotto)',                kcal: 103, p: 21.6, c: 0.0,  f: 1.6,  tags: ['rombo'] },
  { name: 'Cernia (cotta)',               kcal: 92,  p: 19.3, c: 0.0,  f: 1.3,  tags: ['cernia'] },
  { name: 'Halibut (cotto)',              kcal: 140, p: 26.7, c: 0.0,  f: 2.9,  tags: ['halibut'] },
  { name: 'Tilapia (cotta)',              kcal: 128, p: 26.2, c: 0.0,  f: 2.7,  tags: ['tilapia'] },
  { name: 'Anguilla (cotta)',             kcal: 236, p: 18.4, c: 0.0,  f: 18.0, tags: ['anguilla'] },
  { name: 'Gamberetti (cotti)',           kcal: 99,  p: 20.9, c: 0.2,  f: 1.7,  tags: ['gamberi', 'gamberoni', 'shrimp'] },
  { name: 'Calamari (cotti)',             kcal: 92,  p: 15.6, c: 3.1,  f: 1.4,  tags: ['calamari', 'totano'] },
  { name: 'Polpo (cotto)',                kcal: 82,  p: 14.9, c: 2.2,  f: 1.0,  tags: ['polpo'] },
  { name: 'Cozze (cotte)',                kcal: 86,  p: 11.9, c: 3.7,  f: 2.2,  tags: ['cozze', 'muscoli', 'mitili'] },
  { name: 'Vongole (cotte)',              kcal: 74,  p: 12.8, c: 2.0,  f: 1.0,  tags: ['vongole', 'spaghetti alle vongole'] },
  { name: 'Capesante (cotte)',            kcal: 112, p: 20.5, c: 3.2,  f: 1.5,  tags: ['capesante', 'Saint Jacques'] },
  { name: 'Seppia (cotta)',               kcal: 79,  p: 16.2, c: 0.7,  f: 1.0,  tags: ['seppie'] },
  { name: 'Granchio (cotto)',             kcal: 97,  p: 18.1, c: 0.0,  f: 2.1,  tags: ['granchio'] },
  { name: 'Astice (cotto)',               kcal: 89,  p: 18.8, c: 0.5,  f: 1.0,  tags: ['astice', 'aragosta', 'lobster'] },

  // ── UOVA ──────────────────────────────────────────────────────────────────
  { name: 'Uovo intero (crudo)',          kcal: 147, p: 12.6, c: 0.7,  f: 10.6, tags: ['uova crude', 'egg'] },
  { name: 'Uovo sodo',                   kcal: 155, p: 13.0, c: 1.1,  f: 10.6, tags: ['uova sode', 'hard boiled egg'] },
  { name: 'Uova strapazzate (con latte)', kcal: 147, p: 10.0, c: 1.6,  f: 11.4, tags: ['uova strapazzate', 'scrambled eggs', 'uova sbattute'] },
  { name: 'Uova al tegamino (con burro)', kcal: 196, p: 12.5, c: 0.5,  f: 16.0, tags: ['uova al tegamino', 'uova fritte', 'fried eggs', 'uovo fritto'] },
  { name: 'Frittata (semplice)',          kcal: 158, p: 11.5, c: 1.0,  f: 12.3, tags: ['frittata'] },
  { name: 'Frittata di verdure',          kcal: 120, p: 9.5,  c: 3.5,  f: 8.0,  tags: ['frittata verdure'] },
  { name: 'Omelette (semplice)',          kcal: 154, p: 11.0, c: 0.5,  f: 11.5, tags: ['omelette', 'omelette semplice'] },
  { name: 'Albume (crudo)',               kcal: 52,  p: 10.9, c: 0.7,  f: 0.2,  tags: ['albumi', 'egg white'] },
  { name: 'Tuorlo (crudo)',               kcal: 352, p: 16.4, c: 0.3,  f: 31.9, tags: ['tuorlo', 'egg yolk'] },

  // ── LATTICINI & FORMAGGI ──────────────────────────────────────────────────
  { name: 'Latte intero',                 kcal: 64,  p: 3.2,  c: 4.7,  f: 3.6,  tags: ['latte intero', 'whole milk'] },
  { name: 'Latte parzialmente scremato',  kcal: 46,  p: 3.5,  c: 4.9,  f: 1.5,  tags: ['latte parziale', 'latte ps'] },
  { name: 'Latte scremato',               kcal: 36,  p: 3.6,  c: 5.1,  f: 0.2,  tags: ['latte scremato', 'skim milk'] },
  { name: 'Latte di soia',                kcal: 33,  p: 3.3,  c: 1.8,  f: 1.8,  tags: ['latte soia', 'soy milk'] },
  { name: 'Latte di mandorla',            kcal: 24,  p: 0.6,  c: 3.2,  f: 1.1,  tags: ['latte mandorla'] },
  { name: 'Latte di avena',               kcal: 47,  p: 1.0,  c: 7.9,  f: 1.5,  tags: ['latte avena', 'oat milk'] },
  { name: 'Latte di cocco (bevanda)',      kcal: 20,  p: 0.3,  c: 3.0,  f: 0.7,  tags: ['latte di cocco'] },
  { name: 'Yogurt greco (0%)',            kcal: 57,  p: 10.0, c: 3.6,  f: 0.3,  tags: ['yogurt greco magro', 'greek yogurt 0'] },
  { name: 'Yogurt greco (2%)',            kcal: 73,  p: 9.9,  c: 3.5,  f: 2.0,  tags: ['yogurt greco', 'greek yogurt'] },
  { name: 'Yogurt greco (5%)',            kcal: 97,  p: 9.0,  c: 3.4,  f: 5.0,  tags: ['yogurt greco intero'] },
  { name: 'Yogurt bianco intero',         kcal: 61,  p: 3.5,  c: 4.7,  f: 3.2,  tags: ['yogurt', 'yogurt bianco'] },
  { name: 'Yogurt alla frutta',           kcal: 95,  p: 3.5,  c: 17.0, f: 1.5,  tags: ['yogurt frutta', 'yogurt con frutta'] },
  { name: 'Ricotta vaccina',              kcal: 146, p: 11.3, c: 3.1,  f: 10.0, tags: ['ricotta', 'ricotta di mucca'] },
  { name: 'Ricotta di pecora',            kcal: 180, p: 10.5, c: 2.5,  f: 14.5, tags: ['ricotta pecora'] },
  { name: 'Mozzarella',                   kcal: 254, p: 18.0, c: 2.2,  f: 19.5, tags: ['mozzarella'] },
  { name: 'Mozzarella light',             kcal: 152, p: 19.9, c: 2.4,  f: 7.2,  tags: ['mozzarella light'] },
  { name: 'Mozzarella di bufala',         kcal: 280, p: 16.8, c: 2.1,  f: 23.0, tags: ['bufala', 'mozzarella bufala'] },
  { name: 'Burrata',                      kcal: 330, p: 14.0, c: 2.8,  f: 29.0, tags: ['burrata'] },
  { name: 'Scamorza affumicata',          kcal: 334, p: 24.5, c: 1.0,  f: 26.0, tags: ['scamorza', 'provola affumicata'] },
  { name: 'Parmigiano Reggiano',          kcal: 392, p: 33.0, c: 0.0,  f: 28.4, tags: ['parmigiano', 'parmesan'] },
  { name: 'Grana Padano',                 kcal: 384, p: 33.0, c: 0.0,  f: 28.0, tags: ['grana padano', 'grana'] },
  { name: 'Pecorino Romano',              kcal: 388, p: 25.8, c: 0.5,  f: 31.5, tags: ['pecorino', 'pecorino romano'] },
  { name: 'Asiago (stagionato)',          kcal: 381, p: 29.5, c: 0.5,  f: 29.0, tags: ['asiago'] },
  { name: 'Fontina',                      kcal: 343, p: 24.0, c: 1.5,  f: 26.8, tags: ['fontina', 'Valle d\'Aosta'] },
  { name: 'Taleggio',                     kcal: 291, p: 20.6, c: 0.5,  f: 22.9, tags: ['taleggio'] },
  { name: 'Gorgonzola',                   kcal: 330, p: 19.0, c: 0.0,  f: 28.0, tags: ['gorgonzola', 'erborinato'] },
  { name: 'Emmental',                     kcal: 382, p: 28.2, c: 0.5,  f: 30.0, tags: ['emmental', 'groviera', 'gruviera'] },
  { name: 'Brie',                         kcal: 324, p: 19.3, c: 0.5,  f: 27.2, tags: ['brie', 'camembert'] },
  { name: 'Provolone dolce',              kcal: 351, p: 25.6, c: 2.1,  f: 27.0, tags: ['provolone'] },
  { name: 'Stracchino / Crescenza',       kcal: 232, p: 15.0, c: 2.5,  f: 18.2, tags: ['stracchino', 'crescenza'] },
  { name: 'Robiola',                      kcal: 270, p: 16.0, c: 2.0,  f: 22.0, tags: ['robiola'] },
  { name: 'Mascarpone',                   kcal: 429, p: 7.3,  c: 3.0,  f: 44.0, tags: ['mascarpone'] },
  { name: 'Philadelphia (formaggio spalmabile)', kcal: 245, p: 5.2, c: 4.2, f: 23.0, tags: ['philadelphia', 'formaggio cremoso', 'cream cheese'] },
  { name: 'Formaggi freschi light',       kcal: 100, p: 11.4, c: 4.0,  f: 4.4,  tags: ['formaggio light', 'philadelphia light'] },
  { name: 'Cottage cheese',              kcal: 98,  p: 11.1, c: 3.4,  f: 4.3,  tags: ['cottage cheese'] },
  { name: 'Fiocchi di latte',            kcal: 99,  p: 12.4, c: 2.7,  f: 4.3,  tags: ['fiocchi di latte', 'quark'] },
  { name: 'Panna da cucina',             kcal: 337, p: 2.3,  c: 2.9,  f: 35.0, tags: ['panna', 'panna liquida'] },
  { name: 'Panna montata',               kcal: 338, p: 2.0,  c: 3.2,  f: 35.0, tags: ['panna montata', 'whipped cream'] },
  { name: 'Burro',                        kcal: 758, p: 0.7,  c: 0.6,  f: 83.4, tags: ['burro'] },

  // ── LEGUMI ────────────────────────────────────────────────────────────────
  { name: 'Ceci (cotti)',                  kcal: 164, p: 8.9,  c: 22.5, f: 2.6,  tags: ['ceci cotti'] },
  { name: 'Ceci in scatola (scolati)',     kcal: 120, p: 6.5,  c: 16.5, f: 1.8,  tags: ['ceci scatola'] },
  { name: 'Lenticchie (cotte)',            kcal: 116, p: 9.0,  c: 16.3, f: 0.5,  tags: ['lenticchie cotte'] },
  { name: 'Lenticchie rosse (cotte)',      kcal: 100, p: 7.6,  c: 14.5, f: 0.5,  tags: ['lenticchie rosse'] },
  { name: 'Fagioli borlotti (cotti)',      kcal: 93,  p: 6.3,  c: 12.1, f: 0.5,  tags: ['borlotti cotti'] },
  { name: 'Fagioli cannellini (cotti)',    kcal: 96,  p: 6.4,  c: 14.8, f: 0.6,  tags: ['cannellini', 'fagioli bianchi'] },
  { name: 'Fagioli neri (cotti)',          kcal: 132, p: 8.9,  c: 23.7, f: 0.5,  tags: ['fagioli neri', 'black beans'] },
  { name: 'Fagioli rossi (cotti)',         kcal: 127, p: 8.7,  c: 22.8, f: 0.5,  tags: ['fagioli rossi', 'kidney beans'] },
  { name: 'Piselli (cotti)',               kcal: 84,  p: 5.4,  c: 14.5, f: 0.2,  tags: ['piselli'] },
  { name: 'Piselli in scatola',            kcal: 69,  p: 5.0,  c: 10.5, f: 0.3,  tags: ['piselli scatola'] },
  { name: 'Fave (cotte)',                  kcal: 72,  p: 7.6,  c: 8.8,  f: 0.3,  tags: ['fave'] },
  { name: 'Edamame (cotti)',               kcal: 121, p: 11.9, c: 8.9,  f: 5.2,  tags: ['edamame', 'soia verde'] },
  { name: 'Tofu compatto',                 kcal: 76,  p: 8.0,  c: 1.9,  f: 4.2,  tags: ['tofu', 'soia'] },
  { name: 'Tofu morbido (silken)',         kcal: 55,  p: 5.3,  c: 2.0,  f: 2.7,  tags: ['tofu morbido', 'tofu silken'] },
  { name: 'Tempeh',                        kcal: 193, p: 19.0, c: 7.6,  f: 10.8, tags: ['tempeh'] },
  { name: 'Soia texturizzata (TVP, secca)', kcal: 298, p: 52.0, c: 22.0, f: 1.0, tags: ['soia texturizzata', 'TVP', 'granulare proteico'] },
  { name: 'Hummus',                        kcal: 177, p: 7.9,  c: 14.5, f: 10.6, tags: ['hummus'] },
  { name: 'Lupini (in salamoia)',          kcal: 119, p: 15.4, c: 0.5,  f: 5.7,  tags: ['lupini'] },
  { name: 'Arachidi (tostate)',            kcal: 567, p: 25.7, c: 16.1, f: 49.2, tags: ['arachidi', 'peanuts'] },

  // ── VERDURE ───────────────────────────────────────────────────────────────
  { name: 'Spinaci (cotti)',              kcal: 23,  p: 2.9,  c: 1.4,  f: 0.5,  tags: ['spinaci cotti'] },
  { name: 'Spinaci (crudi)',              kcal: 23,  p: 2.9,  c: 1.4,  f: 0.4,  tags: ['spinaci crudi', 'baby spinach'] },
  { name: 'Broccoli (cotti)',             kcal: 35,  p: 2.4,  c: 4.8,  f: 0.4,  tags: ['broccoli cotti'] },
  { name: 'Cavolfiore (cotto)',           kcal: 31,  p: 2.5,  c: 4.1,  f: 0.3,  tags: ['cavolfiore'] },
  { name: 'Cavolini di Bruxelles (cotti)', kcal: 43, p: 3.4,  c: 5.5,  f: 0.6,  tags: ['cavolini di bruxelles', 'brussels sprouts'] },
  { name: 'Cavolo cappuccio (crudo)',     kcal: 25,  p: 1.3,  c: 4.2,  f: 0.2,  tags: ['cavolo', 'verza', 'cavolo bianco'] },
  { name: 'Zucchine (cotte)',             kcal: 17,  p: 1.2,  c: 2.5,  f: 0.2,  tags: ['zucchine', 'zucchina'] },
  { name: 'Pomodori (freschi)',           kcal: 18,  p: 0.9,  c: 3.5,  f: 0.2,  tags: ['pomodoro', 'tomato'] },
  { name: 'Pomodorini ciliegino',         kcal: 18,  p: 0.9,  c: 3.5,  f: 0.2,  tags: ['pomodorini', 'cherry tomatoes'] },
  { name: 'Pomodori secchi',              kcal: 213, p: 4.8,  c: 39.5, f: 2.8,  tags: ['pomodori secchi'] },
  { name: 'Pomodori pelati (in scatola)', kcal: 24,  p: 1.1,  c: 4.2,  f: 0.2,  tags: ['pomodori pelati', 'passata', 'polpa'] },
  { name: 'Lattuga romana',               kcal: 17,  p: 1.2,  c: 2.2,  f: 0.3,  tags: ['lattuga', 'insalata'] },
  { name: 'Lattuga iceberg',              kcal: 14,  p: 0.9,  c: 2.5,  f: 0.1,  tags: ['iceberg', 'insalata iceberg'] },
  { name: 'Rucola',                       kcal: 25,  p: 2.6,  c: 2.0,  f: 0.7,  tags: ['rucola', 'rughetta'] },
  { name: 'Radicchio',                    kcal: 23,  p: 1.5,  c: 3.6,  f: 0.3,  tags: ['radicchio', 'cicoria rossa'] },
  { name: 'Insalata mista',               kcal: 15,  p: 1.3,  c: 1.8,  f: 0.2,  tags: ['insalata mista', 'misticanza'] },
  { name: 'Indivia / Scarola',            kcal: 17,  p: 1.3,  c: 2.0,  f: 0.2,  tags: ['indivia', 'scarola', 'cicoria'] },
  { name: 'Cetrioli',                     kcal: 12,  p: 0.6,  c: 2.2,  f: 0.1,  tags: ['cetriolo'] },
  { name: 'Peperoni (freschi)',           kcal: 27,  p: 1.0,  c: 5.5,  f: 0.3,  tags: ['peperone', 'pepper'] },
  { name: 'Peperoni (grigliati)',         kcal: 32,  p: 1.0,  c: 6.8,  f: 0.2,  tags: ['peperoni grigliati'] },
  { name: 'Carote',                       kcal: 35,  p: 0.9,  c: 7.1,  f: 0.2,  tags: ['carota'] },
  { name: 'Sedano',                       kcal: 14,  p: 0.7,  c: 2.2,  f: 0.2,  tags: ['sedano'] },
  { name: 'Finocchio',                    kcal: 19,  p: 1.2,  c: 2.6,  f: 0.2,  tags: ['finocchio'] },
  { name: 'Funghi champignon',            kcal: 22,  p: 3.1,  c: 1.7,  f: 0.3,  tags: ['funghi', 'champignon', 'mushroom'] },
  { name: 'Funghi porcini (freschi)',     kcal: 27,  p: 3.7,  c: 0.4,  f: 0.5,  tags: ['porcini', 'funghi porcini'] },
  { name: 'Asparagi (cotti)',             kcal: 22,  p: 2.3,  c: 1.8,  f: 0.2,  tags: ['asparagi'] },
  { name: 'Melanzane (cotte)',            kcal: 35,  p: 0.8,  c: 5.7,  f: 0.2,  tags: ['melanzane'] },
  { name: 'Cipolla',                      kcal: 40,  p: 1.1,  c: 8.6,  f: 0.1,  tags: ['cipolla', 'cipolle'] },
  { name: 'Cipolla rossa',                kcal: 38,  p: 1.0,  c: 8.2,  f: 0.1,  tags: ['cipolla rossa'] },
  { name: 'Porri',                        kcal: 31,  p: 1.5,  c: 6.0,  f: 0.3,  tags: ['porro', 'porri'] },
  { name: 'Aglio',                        kcal: 149, p: 6.4,  c: 31.0, f: 0.5,  tags: ['aglio'] },
  { name: 'Patate (cotte)',               kcal: 93,  p: 2.0,  c: 21.1, f: 0.1,  tags: ['patate cotte', 'potato'] },
  { name: 'Patate (crude)',               kcal: 77,  p: 2.0,  c: 17.5, f: 0.1,  tags: ['patate crude'] },
  { name: 'Patate dolci (cotte)',         kcal: 90,  p: 2.0,  c: 20.7, f: 0.1,  tags: ['patata dolce', 'sweet potato', 'batata'] },
  { name: 'Zucca (cotta)',                kcal: 26,  p: 1.0,  c: 4.9,  f: 0.1,  tags: ['zucca'] },
  { name: 'Barbabietola rossa',           kcal: 43,  p: 1.6,  c: 9.6,  f: 0.1,  tags: ['barbabietola', 'bietola rossa'] },
  { name: 'Bietola (cotta)',              kcal: 20,  p: 1.9,  c: 2.1,  f: 0.3,  tags: ['bietola', 'coste'] },
  { name: 'Carciofi (cotti)',             kcal: 53,  p: 2.9,  c: 9.9,  f: 0.2,  tags: ['carciofi', 'carciofo'] },
  { name: 'Fagiolini (cotti)',            kcal: 31,  p: 1.8,  c: 5.7,  f: 0.2,  tags: ['fagiolini'] },
  { name: 'Mais in scatola',              kcal: 86,  p: 3.3,  c: 18.0, f: 1.2,  tags: ['mais', 'granoturco', 'corn'] },
  { name: 'Olive verdi',                  kcal: 145, p: 1.0,  c: 3.8,  f: 15.3, tags: ['olive verdi'] },
  { name: 'Olive nere',                   kcal: 115, p: 0.8,  c: 6.3,  f: 11.0, tags: ['olive nere'] },
  { name: 'Avocado',                      kcal: 160, p: 2.0,  c: 8.5,  f: 14.7, tags: ['avocado'] },
  { name: 'Ravanelli',                    kcal: 16,  p: 0.7,  c: 3.0,  f: 0.1,  tags: ['ravanello'] },
  { name: 'Topinambur',                   kcal: 73,  p: 2.0,  c: 17.4, f: 0.0,  tags: ['topinambur', 'carciofo di gerusalemme'] },

  // ── FRUTTA FRESCA ─────────────────────────────────────────────────────────
  { name: 'Banana',                       kcal: 89,  p: 1.1,  c: 22.8, f: 0.3,  tags: ['banane'] },
  { name: 'Mela',                         kcal: 52,  p: 0.3,  c: 13.8, f: 0.2,  tags: ['mele', 'apple'] },
  { name: 'Arancia',                      kcal: 47,  p: 0.9,  c: 11.0, f: 0.1,  tags: ['arance', 'orange'] },
  { name: 'Mandarino / Clementina',       kcal: 53,  p: 0.8,  c: 13.3, f: 0.3,  tags: ['mandarino', 'clementina', 'tangerine'] },
  { name: 'Pera',                         kcal: 57,  p: 0.4,  c: 15.3, f: 0.1,  tags: ['pere'] },
  { name: 'Pesche',                       kcal: 39,  p: 0.9,  c: 9.5,  f: 0.3,  tags: ['pesca', 'nettarina', 'pesche'] },
  { name: 'Albicocche',                   kcal: 48,  p: 1.4,  c: 11.1, f: 0.4,  tags: ['albicocca', 'apricot'] },
  { name: 'Ciliegie',                     kcal: 63,  p: 1.1,  c: 16.0, f: 0.2,  tags: ['ciliegia', 'cherry'] },
  { name: 'Prugne / Susine',              kcal: 46,  p: 0.7,  c: 11.4, f: 0.3,  tags: ['prugna', 'susina', 'plum'] },
  { name: 'Uva',                          kcal: 69,  p: 0.7,  c: 17.1, f: 0.2,  tags: ['uva', 'grape'] },
  { name: 'Fragole',                      kcal: 32,  p: 0.7,  c: 7.7,  f: 0.3,  tags: ['fragola', 'strawberry'] },
  { name: 'Mirtilli',                     kcal: 57,  p: 0.7,  c: 14.5, f: 0.3,  tags: ['mirtillo', 'blueberry'] },
  { name: 'Lamponi',                      kcal: 52,  p: 1.2,  c: 11.9, f: 0.7,  tags: ['lampone', 'raspberry'] },
  { name: 'More',                         kcal: 43,  p: 1.4,  c: 9.6,  f: 0.5,  tags: ['mora', 'blackberry'] },
  { name: 'Ribes rosso',                  kcal: 56,  p: 1.4,  c: 13.8, f: 0.2,  tags: ['ribes'] },
  { name: 'Ananas',                       kcal: 50,  p: 0.5,  c: 13.1, f: 0.1,  tags: ['pineapple', 'ananas'] },
  { name: 'Mango',                        kcal: 60,  p: 0.8,  c: 15.0, f: 0.4,  tags: ['mango'] },
  { name: 'Kiwi',                         kcal: 61,  p: 1.1,  c: 14.7, f: 0.5,  tags: ['kiwi'] },
  { name: 'Anguria / Cocomero',           kcal: 30,  p: 0.6,  c: 7.6,  f: 0.2,  tags: ['anguria', 'cocomero', 'watermelon'] },
  { name: 'Melone',                       kcal: 36,  p: 0.9,  c: 8.1,  f: 0.3,  tags: ['melone'] },
  { name: 'Pompelmo',                     kcal: 42,  p: 0.8,  c: 10.7, f: 0.1,  tags: ['pompelmo', 'grapefruit'] },
  { name: 'Limone',                       kcal: 29,  p: 1.1,  c: 9.3,  f: 0.3,  tags: ['limone', 'succo di limone'] },
  { name: 'Lime',                         kcal: 30,  p: 0.7,  c: 10.5, f: 0.2,  tags: ['lime'] },
  { name: 'Fichi freschi',                kcal: 74,  p: 0.8,  c: 19.2, f: 0.3,  tags: ['fico fresco'] },
  { name: 'Melograno',                    kcal: 83,  p: 1.7,  c: 18.7, f: 1.2,  tags: ['melograno', 'pomegranate'] },
  { name: 'Papaya',                       kcal: 43,  p: 0.5,  c: 10.8, f: 0.3,  tags: ['papaya'] },
  { name: 'Frutto della passione',        kcal: 97,  p: 2.2,  c: 23.4, f: 0.7,  tags: ['passion fruit', 'maracuja'] },
  { name: 'Cocco fresco',                 kcal: 354, p: 3.3,  c: 15.2, f: 33.5, tags: ['cocco', 'coconut'] },
  { name: 'Castagne (arrosto)',            kcal: 245, p: 3.2,  c: 53.3, f: 2.2,  tags: ['castagne', 'marroni'] },

  // ── FRUTTA SECCA & SEMI ───────────────────────────────────────────────────
  { name: 'Mandorle',                     kcal: 579, p: 21.2, c: 21.7, f: 49.9, tags: ['mandorla', 'almond'] },
  { name: 'Noci',                         kcal: 654, p: 15.2, c: 13.7, f: 65.2, tags: ['noce', 'walnut'] },
  { name: 'Nocciole',                     kcal: 628, p: 15.0, c: 16.7, f: 60.8, tags: ['nocciola', 'hazelnut'] },
  { name: 'Anacardi',                     kcal: 553, p: 18.2, c: 30.2, f: 43.8, tags: ['anacardo', 'cashew'] },
  { name: 'Pistacchi',                    kcal: 562, p: 20.6, c: 27.2, f: 45.3, tags: ['pistacchio', 'pistachio'] },
  { name: 'Pinoli',                       kcal: 673, p: 13.7, c: 13.1, f: 68.4, tags: ['pinoli', 'pine nuts'] },
  { name: 'Noci brasiliane',              kcal: 659, p: 14.3, c: 11.7, f: 67.1, tags: ['noci brasiliane', 'brazil nuts'] },
  { name: 'Noci di macadamia',            kcal: 718, p: 7.9,  c: 13.8, f: 75.8, tags: ['macadamia'] },
  { name: 'Burro di arachidi',            kcal: 588, p: 25.1, c: 20.0, f: 50.4, tags: ['peanut butter', 'crema arachidi'] },
  { name: 'Semi di chia',                 kcal: 486, p: 16.5, c: 42.1, f: 30.7, tags: ['chia'] },
  { name: 'Semi di lino',                 kcal: 534, p: 18.3, c: 28.9, f: 42.2, tags: ['lino', 'flax', 'semi di lino'] },
  { name: 'Semi di zucca',                kcal: 559, p: 30.2, c: 10.7, f: 49.1, tags: ['semi zucca', 'pumpkin seeds'] },
  { name: 'Semi di girasole',             kcal: 584, p: 20.8, c: 20.0, f: 51.5, tags: ['semi girasole', 'sunflower seeds'] },
  { name: 'Semi di canapa',               kcal: 553, p: 31.6, c: 8.7,  f: 48.8, tags: ['semi di canapa', 'hemp seeds'] },
  { name: 'Semi di sesamo',               kcal: 573, p: 17.7, c: 23.4, f: 49.7, tags: ['sesamo', 'sesame'] },
  { name: 'Tahini (crema di sesamo)',      kcal: 595, p: 17.0, c: 21.2, f: 53.8, tags: ['tahini', 'tahin'] },
  { name: 'Cocco essiccato (grattugiato)', kcal: 660, p: 6.9,  c: 23.7, f: 64.5, tags: ['cocco grattugiato', 'farina di cocco'] },
  { name: 'Dattero secco',               kcal: 277, p: 1.8,  c: 74.9, f: 0.2,  tags: ['datteri', 'dates'] },
  { name: 'Uvetta',                       kcal: 299, p: 3.1,  c: 79.2, f: 0.5,  tags: ['uva passa', 'uvetta', 'raisins'] },
  { name: 'Albicocche secche',            kcal: 241, p: 3.4,  c: 62.6, f: 0.5,  tags: ['albicocche essiccate'] },
  { name: 'Fichi secchi',                 kcal: 249, p: 3.3,  c: 63.9, f: 0.9,  tags: ['fichi secchi', 'dried figs'] },

  // ── OLI & GRASSI ─────────────────────────────────────────────────────────
  { name: 'Olio extravergine di oliva',   kcal: 884, p: 0.0,  c: 0.0,  f: 100.0, tags: ['olio evo', 'olio oliva', 'evo'] },
  { name: 'Olio di semi di girasole',     kcal: 884, p: 0.0,  c: 0.0,  f: 100.0, tags: ['olio girasole'] },
  { name: 'Olio di cocco',               kcal: 892, p: 0.0,  c: 0.0,  f: 99.1,  tags: ['olio di cocco', 'coconut oil'] },
  { name: 'Olio di mais',                kcal: 884, p: 0.0,  c: 0.0,  f: 100.0, tags: ['olio mais'] },
  { name: 'Burro',                        kcal: 758, p: 0.7,  c: 0.6,  f: 83.4,  tags: ['burro'] },
  { name: 'Margarina',                    kcal: 717, p: 0.6,  c: 0.5,  f: 79.3,  tags: ['margarina'] },

  // ── CONDIMENTI & SALSE ────────────────────────────────────────────────────
  { name: 'Maionese',                     kcal: 680, p: 1.0,  c: 2.0,  f: 75.0, tags: ['maionese', 'mayo'] },
  { name: 'Ketchup',                      kcal: 101, p: 1.7,  c: 25.0, f: 0.1,  tags: ['ketchup'] },
  { name: 'Senape',                       kcal: 66,  p: 4.4,  c: 5.8,  f: 3.5,  tags: ['senape', 'mustard'] },
  { name: 'Salsa di soia',               kcal: 53,  p: 8.1,  c: 4.8,  f: 0.6,  tags: ['soia salsa', 'soy sauce'] },
  { name: 'Aceto balsamico',             kcal: 88,  p: 0.5,  c: 17.0, f: 0.0,  tags: ['balsamico', 'aceto balsamico'] },
  { name: 'Aceto di vino bianco',        kcal: 21,  p: 0.0,  c: 0.7,  f: 0.0,  tags: ['aceto', 'aceto bianco'] },
  { name: 'Pesto genovese (basilico)',    kcal: 453, p: 5.4,  c: 3.8,  f: 46.3, tags: ['pesto', 'pesto basilico'] },
  { name: 'Salsa di pomodoro (sugo)',     kcal: 49,  p: 2.0,  c: 8.7,  f: 0.5,  tags: ['sugo', 'passata di pomodoro', 'salsa pomodoro'] },
  { name: 'Passata di pomodoro',         kcal: 35,  p: 1.6,  c: 6.5,  f: 0.2,  tags: ['passata'] },
  { name: 'Concentrato di pomodoro',     kcal: 82,  p: 4.3,  c: 15.8, f: 0.5,  tags: ['concentrato pomodoro', 'doppio concentrato'] },
  { name: 'Besciamella',                 kcal: 102, p: 3.3,  c: 8.5,  f: 6.0,  tags: ['besciamella', 'bechamel'] },
  { name: 'Brodo di pollo',              kcal: 15,  p: 1.5,  c: 0.5,  f: 0.5,  tags: ['brodo pollo', 'chicken broth'] },
  { name: 'Brodo vegetale',              kcal: 10,  p: 0.5,  c: 1.5,  f: 0.2,  tags: ['brodo vegetale'] },
  { name: 'Salsa tartara',               kcal: 376, p: 1.2,  c: 8.5,  f: 38.0, tags: ['tartara'] },
  { name: 'Crema di nocciole (Nutella)', kcal: 539, p: 6.3,  c: 57.5, f: 30.9, tags: ['nutella', 'crema nocciole', 'crema di nocciole'] },
  { name: 'Miele',                       kcal: 304, p: 0.3,  c: 82.4, f: 0.0,  tags: ['miele', 'honey'] },
  { name: 'Zucchero bianco',             kcal: 387, p: 0.0,  c: 100.0, f: 0.0, tags: ['zucchero', 'sugar'] },
  { name: 'Zucchero di canna',           kcal: 377, p: 0.1,  c: 97.0, f: 0.0,  tags: ['zucchero di canna', 'brown sugar'] },

  // ── DOLCI & SNACK ─────────────────────────────────────────────────────────
  { name: 'Cioccolato fondente (70%)',    kcal: 598, p: 7.0,  c: 46.0, f: 42.6, tags: ['cioccolato fondente', 'dark chocolate'] },
  { name: 'Cioccolato al latte',         kcal: 535, p: 7.7,  c: 59.2, f: 29.7, tags: ['cioccolato latte', 'milk chocolate'] },
  { name: 'Cioccolato bianco',           kcal: 539, p: 5.9,  c: 59.4, f: 32.1, tags: ['cioccolato bianco', 'white chocolate'] },
  { name: 'Cornetto / Brioche',          kcal: 370, p: 6.5,  c: 49.0, f: 16.0, tags: ['cornetto', 'brioche', 'croissant'] },
  { name: 'Biscotti secchi (tipo Digestive)', kcal: 471, p: 6.2, c: 64.0, f: 20.0, tags: ['biscotti', 'digestive', 'biscotto'] },
  { name: 'Biscotti al burro (tipo frollini)', kcal: 497, p: 5.8, c: 66.0, f: 23.5, tags: ['frollini', 'biscotti burro'] },
  { name: 'Cantucci',                    kcal: 435, p: 11.3, c: 66.5, f: 14.0, tags: ['cantucci', 'biscotti di Prato'] },
  { name: 'Savoiardi',                   kcal: 395, p: 7.1,  c: 73.0, f: 8.5,  tags: ['savoiardi', 'ladyfinger'] },
  { name: 'Wafer al cioccolato',         kcal: 495, p: 6.4,  c: 63.0, f: 23.0, tags: ['wafer'] },
  { name: 'Marmellata',                  kcal: 250, p: 0.6,  c: 65.0, f: 0.0,  tags: ['marmellata', 'confettura', 'jam'] },
  { name: 'Gelato alla frutta (sorbetto)', kcal: 95, p: 0.4, c: 23.5, f: 0.1,  tags: ['sorbetto', 'gelato frutta'] },
  { name: 'Gelato alla crema / cioccolato', kcal: 185, p: 3.5, c: 24.0, f: 8.5, tags: ['gelato', 'ice cream', 'gelato cioccolato'] },
  { name: 'Torta margherita (fetta)',    kcal: 360, p: 7.0,  c: 53.0, f: 13.5, tags: ['torta', 'torta margherita', 'pan di spagna'] },
  { name: 'Crostata con marmellata (fetta)', kcal: 320, p: 4.5, c: 52.0, f: 10.5, tags: ['crostata'] },
  { name: 'Tiramisù (porzione)',         kcal: 280, p: 5.0,  c: 28.0, f: 16.0, tags: ['tiramisù', 'tiramisu'] },
  { name: 'Panna cotta (porzione)',      kcal: 225, p: 3.0,  c: 22.0, f: 13.5, tags: ['panna cotta'] },
  { name: 'Budino al cioccolato',        kcal: 162, p: 4.2,  c: 25.0, f: 5.5,  tags: ['budino', 'pudding'] },
  { name: 'Chips di patate',             kcal: 536, p: 7.0,  c: 53.0, f: 33.0, tags: ['chips', 'patatine', 'crisps'] },
  { name: 'Popcorn (al burro)',          kcal: 424, p: 7.8,  c: 78.0, f: 10.0, tags: ['popcorn'] },
  { name: 'Barretta ai cereali',         kcal: 380, p: 5.5,  c: 65.0, f: 10.0, tags: ['barretta cereali', 'muesli bar'] },
  { name: 'Riso soffiato',               kcal: 381, p: 6.5,  c: 87.7, f: 0.5,  tags: ['riso soffiato', 'puffed rice'] },

  // ── BEVANDE ───────────────────────────────────────────────────────────────
  { name: 'Acqua',                        kcal: 0,   p: 0.0,  c: 0.0,  f: 0.0, tags: ['acqua', 'water'] },
  { name: 'Acqua frizzante',              kcal: 0,   p: 0.0,  c: 0.0,  f: 0.0, tags: ['acqua frizzante', 'sparkling water'] },
  { name: 'Caffè espresso',               kcal: 2,   p: 0.1,  c: 0.0,  f: 0.0, tags: ['caffè', 'espresso', 'coffee'] },
  { name: 'Caffè macchiato',              kcal: 15,  p: 0.7,  c: 1.2,  f: 0.5, tags: ['macchiato'] },
  { name: 'Cappuccino',                   kcal: 60,  p: 3.8,  c: 5.5,  f: 2.5, tags: ['cappuccino'] },
  { name: 'Latte macchiato',              kcal: 55,  p: 3.0,  c: 5.5,  f: 1.5, tags: ['latte macchiato'] },
  { name: 'Tè verde (infuso)',            kcal: 1,   p: 0.0,  c: 0.2,  f: 0.0, tags: ['tè verde', 'green tea'] },
  { name: 'Tè nero (infuso)',             kcal: 1,   p: 0.1,  c: 0.3,  f: 0.0, tags: ['tè', 'tè nero', 'black tea'] },
  { name: 'Tisana (infuso)',              kcal: 1,   p: 0.0,  c: 0.2,  f: 0.0, tags: ['tisana', 'herbal tea'] },
  { name: 'Succo d\'arancia',             kcal: 45,  p: 0.7,  c: 10.4, f: 0.2, tags: ['succo arancia', 'orange juice'] },
  { name: 'Succo di mela',               kcal: 46,  p: 0.1,  c: 11.3, f: 0.1, tags: ['succo mela', 'apple juice'] },
  { name: 'Succo di pomodoro',           kcal: 17,  p: 0.9,  c: 3.5,  f: 0.1, tags: ['succo pomodoro', 'tomato juice'] },
  { name: 'Coca Cola',                   kcal: 42,  p: 0.0,  c: 10.6, f: 0.0, tags: ['coca cola', 'cola', 'gassosa'] },
  { name: 'Acqua tonica',                kcal: 34,  p: 0.0,  c: 8.8,  f: 0.0, tags: ['tonica', 'tonic water'] },
  { name: 'Birra (media)',               kcal: 43,  p: 0.5,  c: 3.6,  f: 0.0, tags: ['birra', 'beer'] },
  { name: 'Vino rosso',                  kcal: 85,  p: 0.1,  c: 2.3,  f: 0.0, tags: ['vino rosso', 'red wine'] },
  { name: 'Vino bianco',                 kcal: 82,  p: 0.1,  c: 2.0,  f: 0.0, tags: ['vino bianco', 'white wine'] },
  { name: 'Prosecco',                    kcal: 68,  p: 0.1,  c: 1.0,  f: 0.0, tags: ['prosecco', 'spumante', 'champagne'] },
  { name: 'Smoothie misto frutta',       kcal: 60,  p: 0.8,  c: 14.5, f: 0.2, tags: ['smoothie', 'frullato'] },
  { name: 'Latte di riso',               kcal: 47,  p: 0.3,  c: 9.5,  f: 1.0, tags: ['latte di riso', 'rice milk'] },

  // ── INTEGRATORI ───────────────────────────────────────────────────────────
  { name: 'Whey Protein (polvere)',        kcal: 380, p: 75.0, c: 8.0,  f: 5.0,  tags: ['whey', 'proteina siero', 'protein powder', 'proteine'] },
  { name: 'Caseina (polvere)',             kcal: 375, p: 80.0, c: 5.0,  f: 3.0,  tags: ['casein', 'caseina'] },
  { name: 'Proteine vegetali (polvere)',   kcal: 360, p: 70.0, c: 10.0, f: 5.0,  tags: ['proteine vegetali', 'vegan protein', 'plant protein'] },
  { name: 'Albumina (polvere)',            kcal: 350, p: 80.0, c: 5.0,  f: 0.5,  tags: ['albumina', 'egg white powder'] },
  { name: 'Gainer (polvere)',              kcal: 370, p: 22.0, c: 65.0, f: 3.0,  tags: ['mass gainer', 'gainer'] },
  { name: 'Creatina',                     kcal: 0,   p: 0.0,  c: 0.0,  f: 0.0,  tags: ['creatina', 'creatine'] },
  { name: 'BCAA (polvere)',               kcal: 200, p: 50.0, c: 0.0,  f: 0.0,  tags: ['bcaa', 'aminoacidi ramificati'] },
  { name: 'Glutammina (polvere)',         kcal: 0,   p: 0.0,  c: 0.0,  f: 0.0,  tags: ['glutammina', 'glutamine'] },
  { name: 'Maltodestrine',               kcal: 387, p: 0.1,  c: 95.0, f: 0.0,  tags: ['malto', 'carboidrati', 'maltodextrin'] },
  { name: 'Ciclodestrine (Cluster Dextrin)', kcal: 380, p: 0.0, c: 95.0, f: 0.0, tags: ['ciclodestrine', 'cluster dextrin', 'HBCD'] },
  { name: 'Omega-3 (olio di pesce)',      kcal: 902, p: 0.0,  c: 0.0,  f: 100.0, tags: ['omega3', 'omega-3', 'fish oil'] },
  { name: 'Barretta proteica media',      kcal: 350, p: 28.0, c: 35.0, f: 8.0,  tags: ['barretta', 'protein bar', 'barretta proteica'] },
  { name: 'Gel energetico',               kcal: 110, p: 0.5,  c: 27.0, f: 0.1,  tags: ['gel', 'energy gel', 'gel energetico'] },

  // ── PIATTI ITALIANI PRONTI / RICETTE ────────────────────────────────────
  { name: 'Pizza margherita (forno)',     kcal: 250, p: 11.0, c: 33.0, f: 8.0,  tags: ['pizza'] },
  { name: 'Pizza marinara',              kcal: 190, p: 6.5,  c: 33.5, f: 3.8,  tags: ['pizza marinara'] },
  { name: 'Pasta al ragù / Bolognese',   kcal: 185, p: 8.0,  c: 26.0, f: 5.5,  tags: ['ragù', 'bolognese', 'pasta carne'] },
  { name: 'Pasta alla carbonara',        kcal: 225, p: 9.5,  c: 27.5, f: 8.5,  tags: ['carbonara'] },
  { name: 'Pasta all\'amatriciana',      kcal: 210, p: 7.5,  c: 29.0, f: 6.5,  tags: ['amatriciana'] },
  { name: 'Pasta cacio e pepe',          kcal: 200, p: 7.5,  c: 28.5, f: 6.0,  tags: ['cacio e pepe'] },
  { name: 'Pasta al pesto',              kcal: 215, p: 6.5,  c: 26.5, f: 8.5,  tags: ['pasta pesto'] },
  { name: 'Pasta all\'arrabbiata',       kcal: 165, p: 6.0,  c: 28.0, f: 3.5,  tags: ['arrabbiata'] },
  { name: 'Pasta alle vongole',          kcal: 168, p: 8.5,  c: 25.5, f: 3.5,  tags: ['vongole', 'pasta vongole'] },
  { name: 'Spaghetti aglio, olio e peperoncino', kcal: 195, p: 5.8, c: 27.5, f: 7.0, tags: ['aglio olio', 'aglio e olio'] },
  { name: 'Lasagna al ragù',             kcal: 160, p: 8.5,  c: 15.5, f: 7.0,  tags: ['lasagna', 'lasagne'] },
  { name: 'Lasagna vegetariana',         kcal: 130, p: 6.5,  c: 14.5, f: 5.5,  tags: ['lasagna veg', 'lasagne verdure'] },
  { name: 'Risotto ai funghi',           kcal: 145, p: 4.5,  c: 26.0, f: 3.0,  tags: ['risotto funghi'] },
  { name: 'Risotto allo zafferano',      kcal: 155, p: 4.0,  c: 28.5, f: 3.5,  tags: ['risotto zafferano', 'risotto alla milanese'] },
  { name: 'Risotto al pomodoro',         kcal: 142, p: 3.8,  c: 28.0, f: 2.0,  tags: ['risotto pomodoro', 'risotto'] },
  { name: 'Cotoletta alla milanese',     kcal: 330, p: 22.0, c: 15.0, f: 20.0, tags: ['cotoletta', 'milanesa'] },
  { name: 'Scaloppine al limone',        kcal: 145, p: 21.0, c: 2.5,  f: 5.5,  tags: ['scaloppine'] },
  { name: 'Pollo alla cacciatora',       kcal: 152, p: 17.0, c: 4.5,  f: 6.8,  tags: ['cacciatora'] },
  { name: 'Pollo al forno con patate',   kcal: 165, p: 18.0, c: 12.0, f: 5.5,  tags: ['pollo patate', 'pollo forno'] },
  { name: 'Bistecca ai ferri',           kcal: 170, p: 25.5, c: 0.0,  f: 7.5,  tags: ['bistecca ferri', 'grigliata', 'bistecca grigliata'] },
  { name: 'Hamburger di manzo (completo)', kcal: 250, p: 14.5, c: 16.0, f: 13.5, tags: ['hamburger completo', 'burger'] },
  { name: 'Parmigiana di melanzane',     kcal: 138, p: 6.5,  c: 7.5,  f: 9.5,  tags: ['parmigiana', 'melanzane parmigiana'] },
  { name: 'Branzino al forno',           kcal: 115, p: 22.5, c: 1.0,  f: 2.5,  tags: ['branzino forno', 'pesce al forno'] },
  { name: 'Salmone al forno',            kcal: 195, p: 19.5, c: 0.5,  f: 12.5, tags: ['salmone forno'] },
  { name: 'Baccalà alla livornese',      kcal: 118, p: 20.5, c: 4.5,  f: 2.5,  tags: ['baccalà livornese'] },
  { name: 'Frittata di patate',          kcal: 148, p: 7.5,  c: 14.5, f: 6.5,  tags: ['frittata patate'] },
  { name: 'Insalata Caprese',            kcal: 170, p: 8.5,  c: 4.0,  f: 13.5, tags: ['caprese', 'insalata caprese'] },
  { name: 'Bruschetta al pomodoro',      kcal: 180, p: 5.0,  c: 31.0, f: 4.5,  tags: ['bruschetta'] },
  { name: 'Ribollita',                   kcal: 65,  p: 3.5,  c: 9.0,  f: 1.5,  tags: ['ribollita', 'zuppa toscana'] },
  { name: 'Minestrone di verdure',       kcal: 45,  p: 2.5,  c: 6.5,  f: 1.0,  tags: ['minestrone', 'zuppa verdure'] },
  { name: 'Zuppa di lenticchie',         kcal: 90,  p: 6.5,  c: 13.0, f: 1.5,  tags: ['zuppa lenticchie', 'minestra lenticchie'] },
  { name: 'Pasta e fagioli',             kcal: 115, p: 5.5,  c: 18.5, f: 2.0,  tags: ['pasta fagioli'] },
  { name: 'Riso in bianco (cotto)',      kcal: 130, p: 2.7,  c: 28.2, f: 0.3,  tags: ['riso bianco cotto', 'riso scondito'] },
  { name: 'Pastina in brodo',            kcal: 55,  p: 2.5,  c: 10.5, f: 0.5,  tags: ['pastina', 'pastina brodo'] },
  { name: 'Insalata di pollo',           kcal: 120, p: 18.5, c: 3.5,  f: 4.0,  tags: ['insalata pollo'] },
  { name: 'Insalata tonno e fagioli',    kcal: 130, p: 14.5, c: 9.5,  f: 3.5,  tags: ['tonno fagioli', 'insalata tonno'] },
  { name: 'Panino con prosciutto cotto', kcal: 220, p: 12.5, c: 28.5, f: 6.5,  tags: ['panino prosciutto', 'tramezzino prosciutto'] },
  { name: 'Piadina con prosciutto e stracchino', kcal: 295, p: 14.0, c: 30.0, f: 13.0, tags: ['piadina prosciutto', 'piadina stracchino'] },
  { name: 'Toast al prosciutto e formaggio', kcal: 240, p: 13.5, c: 25.0, f: 9.5, tags: ['toast', 'toast caldo'] },
  { name: 'Wrap pollo e verdure',        kcal: 195, p: 15.0, c: 22.0, f: 5.5,  tags: ['wrap', 'wrap pollo'] },
  { name: 'Kebab di pollo (pita)',       kcal: 210, p: 16.5, c: 22.5, f: 6.0,  tags: ['kebab pollo'] },

  // ── COLAZIONE ─────────────────────────────────────────────────────────────
  { name: 'Pancakes (classici)',          kcal: 227, p: 6.5,  c: 35.0, f: 7.0,  tags: ['pancakes', 'frittelle'] },
  { name: 'French toast',                kcal: 229, p: 8.5,  c: 26.0, f: 10.5, tags: ['french toast', 'pane fritto uova'] },
  { name: 'Porridge con latte intero',   kcal: 120, p: 4.5,  c: 17.5, f: 3.5,  tags: ['porridge', 'avena latte'] },
  { name: 'Porridge con acqua',          kcal: 71,  p: 2.5,  c: 12.0, f: 1.5,  tags: ['porridge acqua'] },
  { name: 'Uova e toast (piatto)',        kcal: 200, p: 14.0, c: 16.5, f: 8.5,  tags: ['uova toast', 'colazione proteica'] },
  { name: 'Müsli con yogurt',            kcal: 200, p: 8.0,  c: 30.0, f: 5.5,  tags: ['musli yogurt', 'colazione yogurt'] },

  // ── PRODOTTI DA FORNO DOLCI ────────────────────────────────────────────────
  { name: 'Croissant semplice',          kcal: 393, p: 8.2,  c: 46.0, f: 19.0, tags: ['croissant', 'brioche vuota'] },
  { name: 'Muffin al cioccolato',        kcal: 370, p: 5.5,  c: 53.0, f: 15.5, tags: ['muffin'] },
  { name: 'Donut / Ciambella fritta',    kcal: 425, p: 5.0,  c: 54.0, f: 20.0, tags: ['donut', 'ciambella', 'bombolone'] },
  { name: 'Crostata di frutta',          kcal: 295, p: 4.0,  c: 47.0, f: 9.5,  tags: ['crostata frutta'] },
  { name: 'Torta di mele',               kcal: 290, p: 3.5,  c: 47.0, f: 9.5,  tags: ['torta mele'] },
  { name: 'Brownie al cioccolato',       kcal: 430, p: 5.5,  c: 56.0, f: 21.0, tags: ['brownie'] },
]

/**
 * Cerca alimenti nel database locale.
 * Supporta match parziale, insensibile a maiuscole/diacritici.
 */
export function searchFoods(query: string, limit = 6): Food[] {
  const q = normalize(query)
  if (q.length < 2) return []

  const words = q.split(/\s+/).filter(Boolean)

  const scored = FOODS.map(food => {
    const haystack = normalize(food.name + ' ' + (food.tags?.join(' ') ?? ''))
    let score = 0

    // Match esatto del nome
    if (haystack.startsWith(q)) score += 100
    // Match parziale nel nome
    if (haystack.includes(q)) score += 50
    // Ogni parola della query che compare
    for (const w of words) {
      if (haystack.includes(w)) score += 20
      if (normalize(food.name).startsWith(w)) score += 30
    }

    return { food, score }
  })

  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.food)
}

function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')  // rimuove diacritici (à → a)
    .replace(/['']/g, '')
}
